{"uuid": "1b6f5c73-b986-4227-9203-9ace84692f6c", "children": ["fa4934c8-7d22-4497-bc81-1978168a981e"], "befores": [{"name": "base_fixture", "status": "passed", "start": 1630569093832, "stop": 1630569093835}], "afters": [{"name": "base_fixture::0", "status": "failed", "statusDetails": {"message": "Failed: yield_fixture function has more than one 'yield':\n\n    @pytest.yield_fixture(scope ='function', autouse=True)\n    def base_fixture():\n        try:\n            prodpath = open(constants.ENVIRONMENT_PROPERTIES)\n            prod.load(prodpath)\n            #prod.list()\n            base = BasePage()\n            objlist.append(base)\n        except Exception:\n            print(Exception)\n    \n        yield locals()\n        base.quit()\nC:\\Users\\SESA243476\\Documents\\JavaStudyPlan\\EclipseProject\\POM\\conftest.py:14\n", "trace": "  File \"C:\\Users\\SESA243476\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\SESA243476\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 805, in _teardown_yield_fixture\n    fixturefunc, \"yield_fixture function has more than one 'yield'\"\n  File \"C:\\Users\\SESA243476\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 781, in fail_fixturefunc\n    fail(msg + \":\\n\\n\" + str(source.indent()) + \"\\n\" + location, pytrace=False)\n  File \"C:\\Users\\SESA243476\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\_pytest\\outcomes.py\", line 158, in fail\n    raise Failed(msg=msg, pytrace=pytrace)\n"}, "start": 1630569438344, "stop": 1630569438508}], "start": 1630569093832, "stop": 1630569438509}