{"uuid": "17fabba1-7a93-4c18-bb00-68528456b956", "children": ["b9f1c0be-6b8f-4a9f-ba05-7e02d2a97864"], "befores": [{"name": "base_fixture", "status": "passed", "start": 1630570284719, "stop": 1630570287481}], "afters": [{"name": "base_fixture::0", "status": "failed", "statusDetails": {"message": "Failed: yield_fixture function has more than one 'yield':\n\n    @pytest.yield_fixture(scope ='function', autouse=True)\n    def base_fixture():\n        try:\n            prodpath = open(constants.ENVIRONMENT_PROPERTIES)\n            prod.load(prodpath)\n            #prod.list()\n            base = BasePage()\n            objlist.append(base)\n        except Exception:\n            print(Exception)\n    \n        yield locals()\n        base.quit()\nC:\\Users\\SESA243476\\Documents\\JavaStudyPlan\\EclipseProject\\POM\\conftest.py:14\n", "trace": "  File \"C:\\Users\\SESA243476\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\SESA243476\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 805, in _teardown_yield_fixture\n    fixturefunc, \"yield_fixture function has more than one 'yield'\"\n  File \"C:\\Users\\SESA243476\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 781, in fail_fixturefunc\n    fail(msg + \":\\n\\n\" + str(source.indent()) + \"\\n\" + location, pytrace=False)\n  File \"C:\\Users\\SESA243476\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\_pytest\\outcomes.py\", line 158, in fail\n    raise Failed(msg=msg, pytrace=pytrace)\n"}, "start": 1630570292108, "stop": 1630570295482}], "start": 1630570284719, "stop": 1630570295484}